# Use https (public access) instead of git for git-submodules. This modifies only Travis-CI behavior!

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# safelist
branches:
  only:
  - master
  - stable

language: go
install: go get -v github.com/spf13/hugo
script:
  - python --version
  - sudo pip install awscli
  - hugo
  - aws s3 sync --delete public/ s3://techan-fr-public/
  - mkdir ~/.aws
  - echo "[preview]" > ~/.aws/config
  - echo "cloudfront = true" >> ~/.aws/config
  - aws cloudfront create-invalidation --distribution-id E1CZHWYAPM8AOD --paths "/*"
notifications:
    email:
        on_failure: always
