sudo: required

services:
  - docker

language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo

script: hugo -t hugo-future-imperfect-0.3

before_install:
- docker build -t mrraph/blog $HOME/gopath/src/github.com/MrRaph/blog/
- docker login
- docker push mrraph/blog
# before_deploy:
#   pip install --user awscli
# deploy:
#   provider: script
#   script: ~/.local/bin/aws s3 sync public/ s3://www.techan.fr --region=eu-west-1 --delete
#   skip_cleanup: true
