# safelist
branches:
  only:
  - master
  - stable

language: go
install: go get -v github.com/spf13/hugo
script:
  - python --version
  - sudo pip install s3cmd awscli
  - mkdir public
  - s3cmd sync -P -M -r s3://techan-fr-public/ public/
  - hugo
  - s3cmd sync --delete-removed -P -M -r public/ s3://techan-fr-public/
  - mkdir ~/.aws
  - echo "[preview]" > ~/.aws/config
  - echo "cloudfront = true" >> ~/.aws/config
  - aws cloudfront create-invalidation --distribution-id E1CZHWYAPM8AOD --paths "/*"
notifications:
    email:
        on_failure: always
