language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo -t material-design
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.techan.fr
  region: eu-west-1
  endpoint: www.techan.fr.s3-website-eu-west-1.amazonaws.com
  local-dir: public
  skip_cleanup: true
  on:
    repo: MrRaph/blog

