language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo -t material-design-techan

before_deploy:
  pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://www.techan.fr --region=eu-west-1 --delete
  skip_cleanup: true
