theme="hugo-future-imperfect-0.3"
baseurl = "https://techan.fr"
languageCode = "fr-FR"
title = "TechAN"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "techan" # optional
copyright = "© 2016 Copyright Text"

[params]
  description = "Trucs, Astuces et Bidouilles IT" # optional
  twitter = "TechAldanet" # optional
  github = "MrRaph" # optional
  facebook = "TechAldaNet" # optional
  # linkedin = "Your LinkedIn Name" # optional
  headerCover = "images/background.png" # optional
  footerCover = "images/background.png" # optional
  googleAnalyticsUserID = "UA-66138476-1" # optional

  # This will appear on the top left of the navigation bar
  navbarTitle          = "TechAN"
  # Social media buttons that appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
# Optional Params
  categoriesByCount    = true
  includeReadingTime   = true
  # The set of favicons used are based on the write-up from this link:
  # https://github.com/audreyr/favicon-cheat-sheet
  # Please see the favicon partial template for more information
  loadFavicon          = false
  faviconVersion = ""
  showCategories = false
  authorAvatar = "/avatars/mrraph.jpeg"

[permalinks]
  post = "/:slug/" # optional


# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "TechAN"
    paragraph = "Des trucs et astuces, des bidouilles, des infos .... Que du bon quoi ! :-)"
    about     = "Dans ce blog, je partage avec le plus grand nombre tous les petits trucs que je fais dans le cadre de mon travail et qui me demande un effort de recherche ou que je fais régulièrement mais que je documente pour ne plus avoir de recherches supplémentaires a réaliser."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/images/TechAN_petit.png"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = false
    width     = ""
    alt       = "TechAN"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 3

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Catégories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "A Propos"
    url = "/a-propos"
    weight = 3

[[menu.main]]
    name = "Docker"
    url = "/categories/docker/"
    weight = 4    weight = 3

[[menu.main]]
    name = "Trucs et Astuces"
    url = "/categories/trucs-et-astuces/"
    weight = 5

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "MrRaph"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "TechAldanet"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "TechAldanet"
    email = ""
